### ISSUE TITLE
more options for building  UI : jsx, vue..

### ISSUE THREAD

**Issue by elycheikhsmail** [kravetsone/create-elysiajs#22]
I'm curious if we will get more flexibility on the way we build UI using elysiajs like the flexibility in astro ? use any js ui library like reactjs, vuejs, svelte ?

**Comment by kravetsone** [comment]
> I'm curious if we will get more flexibility on the way we build UI using elysiajs like the flexibility in astro ? use any js ui library like reactjs, vuejs, svelte ?

Maybe your issue is directed to [elysia](https://github.com/elysiajs/elysia)?
